name: Check & fix styling
on: [push, pull_request]
jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.head_ref }}
            - name: Run PHP CS Fixer
              uses: docker://oskarstark/php-cs-fixer-ga
            - name: Commit changes
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                  commit_message: Fix styling
